MvcProjeKampi/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());

        public ActionResult Index()
        {
            var headingValues=hm.GetList();

            return View(headingValues);
        }
        public ActionResult AddHeading()
        {
            List<SelectListItem>valueCategory=(from x in cm.GetList()
                                               select new SelectListItem
                                               {
                                                   Text=x.CategoryName,
                                                   Value=x.CategoryID.ToString()
                                               }).ToList();
            List<SelectListItem> valueWriter = (from x in wm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.WriterName + " " +x.WriterSurname,
                                                      Value = x.WriterID.ToString()
                                                  }).ToList();
            ViewBag.vlc=valueCategory;
            ViewBag.vlw = valueWriter;
            return View();
        }
        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            hm.HeadingAdd(heading);
            return RedirectToAction("Index");   
        }

        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valueCategory;

            var headingValue = hm.GetByID(id);
            return View(headingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {
            hm.HeadingUpdate(heading);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteHeading(int id)
        {
            var headingValue = hm.GetByID(id);
            headingValue.HeadingStatus = false;
           
            hm.HeadingDelete(headingValue);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>AddHeading</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Heading</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.HeadingName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HeadingName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HeadingName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HeadingDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HeadingDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HeadingDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Kategori")
        <div class="col-md-10">
            @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" }))
            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Yazar")
        <div class="col-md-10">
            @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" }))
            @Html.ValidationMessageFor(model => model.WriterID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcProjeKampi/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>

@using (Html.BeginForm("EditHeaing","Heading",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Heading</h4>
    <hr />


    <div class="form-group">
        @Html.Label("Başlık ID")
        @Html.TextBoxFor(x => x.HeadingID, new { @class = "form-control" })
        <br />
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <br />
        @Html.Label("Tarih")
        @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })

        <br />

    </div>

      
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MvcProjeKampi/Views/Heading/Index.cshtml
@model IEnumerable<EntityLayer.Concrete.Heading>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@*
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "AddHeading")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Writers.WriterName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HeadingName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HeadingDate)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Writers.WriterName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HeadingName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HeadingDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.HeadingID }) |
                @Html.ActionLink("Details", "Details", new { id=item.HeadingID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.HeadingID })
            </td>
        </tr>
    }

    </table>*@



@{ 
    string color ="";
}
<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Proje İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 30%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 30%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                color= "badge badge - success";

                            }
                            if (item.Category.CategoryName == "Spor")
                            {
                                color = "badge badge - warning";

                            }
                            if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge - secondary";

                            }
                            if (item.Category.CategoryName == "Eğitim")
                            {
                                color = "badge badge - danger";

                            }
                        <tr>
                            <td>
                                @item.HeadingID
                            </td>
                            <td>
                                <a>
                                    @item.HeadingName
                                </a>
                                <br />
                                <small>
                                    @(((DateTime)item.HeadingDate).ToString("dd-MM-yyyy"))
                                    @*@item.HeadingDate*@
                                </small>
                            </td>
                            <td>
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <img alt="Avatar" class="table-avatar" src="~/AdminLTE-3.0.4/dist/img/avatar.png"> @*item.writerImg ile görsellerini getirebilirsin ama db'de tutma'*@
                                    </li>
                                </ul>
                            </td>
                            <td>
                                @item.HeadingStatus
                            </td>
                            <td class="project-state">
                                <span class="@color">@item.Category.CategoryName</span>
                            </td>
                            <td class="project-actions text-right">
                                <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                    <i class="fas fa-folder">
                                    </i>
                                    İçerik
                                </a>
                                <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                    <i class="fas fa-trash">
                                    </i>
                                    Sil
                                </a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
    <a href="/Heading/AddHeading/" class="btn btn-primary">Yeni Başlık Girişi</a>
</body>
</html>